//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapter05.Recipe10.Resources.Web.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chapter05.Recipe10.Resources.Web.Models.AccountViewModelResource", typeof(AccountViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ExternalLoginConfirmationEmail {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ForgotViewModelEmail {
            get {
                return ResourceManager.GetString("ForgotViewModelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LoginViewModelEmail {
            get {
                return ResourceManager.GetString("LoginViewModelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginViewModelPassword {
            get {
                return ResourceManager.GetString("LoginViewModelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string LoginViewModelRemember {
            get {
                return ResourceManager.GetString("LoginViewModelRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RegisterViewModelEmail {
            get {
                return ResourceManager.GetString("RegisterViewModelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is required.
        /// </summary>
        public static string RegisterViewModelEmailRequired {
            get {
                return ResourceManager.GetString("RegisterViewModelEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterViewModelPassword {
            get {
                return ResourceManager.GetString("RegisterViewModelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string RegisterViewModelPasswordCompareError {
            get {
                return ResourceManager.GetString("RegisterViewModelPasswordCompareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string RegisterViewModelPasswordConfirm {
            get {
                return ResourceManager.GetString("RegisterViewModelPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string RegisterViewModelPasswordRequired {
            get {
                return ResourceManager.GetString("RegisterViewModelPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string RegisterViewModelPasswordStringLenError {
            get {
                return ResourceManager.GetString("RegisterViewModelPasswordStringLenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string VerifyCodeViewModelCode {
            get {
                return ResourceManager.GetString("VerifyCodeViewModelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is required.
        /// </summary>
        public static string VerifyCodeViewModelCodeRequiredError {
            get {
                return ResourceManager.GetString("VerifyCodeViewModelCodeRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this Browser.
        /// </summary>
        public static string VerifyCodeViewModeRemember {
            get {
                return ResourceManager.GetString("VerifyCodeViewModeRemember", resourceCulture);
            }
        }
    }
}
